jobs:
  - name: development
    max_in_flight: 1
    plan:
      - get: dataworks-repo-template-terraform
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
      - .: (( inject meta.plan.terraform-plan ))
