jobs:
  - name: qa
    max_in_flight: 1
    plan:
      - get: dataworks-repo-template-terraform
        trigger: true
        passed:
          - development
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'qa'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'qa'
